stages:
  prepare:
    cmd: python src/preprocess.py
    deps:
      - data/UCI_Credit_Card.csv
    outs:
      - data/processed_data.csv

  train:
    cmd: python src/train.py
    deps:
      - data/processed_data.csv
    outs:
      - models/model.pkl